ratio_to_use = "modified_eye_aspect_ratio"
deamonize = false

[draw_info]
resolution = true
fps = true

[draw_landmarks]
face = true
eye = true
mouth = true

[ratio_thresholds]
eye_aspect_ratio = 0.15
magic_ratio = 200
mouth_aspect_ratio = 0.4
modified_eye_aspect_ratio_left = 0.18
modified_eye_aspect_ratio_right = 0.18

[time_thresholds]
eyes_closed = 3
yawn = 4

[show_ratios]
eye_aspect_ratio = true
magic_ratio = true
mouth_aspect_ratio = true
modified_eye_aspect_ratio = true
